flower:
  backup:
    hour: ${BACKUP_HOUR:02:00}
    minute: ${BACKUP_MINUTE:00}
    second: ${BACKUP_SECOND:00}

spring:
  # Batch
  batch:
    job:
      names: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: always
  # Quartz
  quartz:
    scheduler-name: QuartzScheduler
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  h2:
   console:
     enabled: true
     path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/dev;AUTO_SERVER=TRUE
    username: sa
    password: 

logging:
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 7
  level:
    root: INFO
    kr.co.flower.blooming: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%4L] - %m%n"
    file: "[%d{HH:mm:ss.SSS}][%-5level][%t][%logger.%method:line%line] - %msg%n"
  file:
    name: "/tmp/logs/blooming-flower-server-dev.log"