name: Blooming Flower Service CI/CD

on:
  push:
    branches: [ "main" ]

env:
  EC2_HOST: ${{ secrets.BLOOMING_FLOWER_HOST }}
  SERVICE_HOME: ${{ secrets.BLOOMING_FLOWER_HOME }}
  SCRIPT: shell/blooming-flower-deploy.sh
  
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean bootJar
    - name: Copy jar to EC2
      uses: appleboy/scp-action@master
      with:
        username: ${{ secrets.EC2_USERNAME }}
        host: ${{ env.EC2_HOST }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.PRIVATE_KEY }}
        source: "./build/libs/*.jar"
        target: ${{ env.SERVICE_HOME }}
        strip_components: 2
    - name: Execute Script
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.EC2_USERNAME }}
        host: ${{ env.EC2_HOST }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.PRIVATE_KEY }}
        script_stop: true
        script: chmod 744 ${{ env.SERVICE_HOME }}/${{ env.SCRIPT }} && ${{ env.SERVICE_HOME }}/${{ env.SCRIPT }} start

